### ISSUE TITLE
Request for adding property "has database cross reference" to OMO

### ISSUE THREAD

**Issue by matentzn** [information-artifact-ontology/ontology-metadata#123]
### IRI

http://www.geneontology.org/formats/oboInOwl#hasDbXref

### Label

has database cross reference

### Definition of the property

An annotation property that links an ontology entity to a database identifier.

### What is the range of the property in question?

xsd:string

### Examples of use

MONDO:0021125 <http://www.geneontology.org/formats/oboInOwl#hasDbXref> "NCIT:C41009"^^xsd:string

### Motivation to add

oboInOwl:hasDbXref is one of the most widely used annotation properties across OBO Foundry ontologies. 

### ORCID, ROR or Wikidata identifier of the contributor

https://orcid.org/0000-0002-7356-1779

### OMO Checklist

- [X] I believe the property is generally useful beyond my specific ontology needs.
- [X] There is no other property in OMO that covers the same use case.

**Comment by matentzn** [comment]
Note that:

1. The property should _not_ be used to map across OBO Foundry ontologies.
2. The design decision of having the range be xsd:string has been extensively discussed in #59 

Without any further discussion, the specification above reflects current practice and I advice against re-hashing the discussion now. If anything, someone should offer advice on the definition, which I just sucked out of my nose but may not be ideal.

**Comment by matentzn** [comment]
@anitacaron can you take care of this?

**Comment by gouttegd** [comment]
Replying here to your request for comments on Slack (“What is the ideal label (and definition) for oboInOwl:hasDbXref?”):

Should the label and definition reflects how the property is _supposed_ to be used, or how it is used effectively?

If it’s supposed to reflect how the property is effectively used in the wild, then I’d suggest to drop the “database“ part, because the property is certainly not used exclusively to point to database entries (in particular, and contrary to what the note says, it _is_ intensively used to “map across OBO Foundry ontologies“).

I’d suggest:

* label: “has cross-reference“
* definition: “An annotation property that points to an identifier of some sort.”
