### ISSUE TITLE
How to indicate which ontology the term is managed by?

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/ontology-metadata#126]
It seems that one ontology can adopt a term from another ontology. So, we cannot know which ontology the term is managed by based on the term ID prefix. We may use an annotation property to specify the home of the term.

@matentzn proposed to use rdf:isDefinedBy, see the discussion: [OBO issue #1676](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1676)

@alanruttenberg proposed to add a new annotation property, "is curated in ontology" since rdf:isDefinedBy may be being used in different ways, see the discussion: [IAO issue 266](https://github.com/information-artifact-ontology/IAO/issues/266)

**Comment by matentzn** [comment]
Do you really want to open that for discussion again? Since it's been decided over a year ago, we have implemented this in ROBOT and in some of our ontology pipelines. We cant just change that now again without a good reason! 

The more interesting question is the question of wether to adopt terms from other ontologies or migrate them (obsolete + replace). Since I am sure this issue will cause another 2 years of productive discussions we may as well start right now! :)

**Comment by zhengj2007** [comment]
@matentzn I saw you mentioned in the [IAO issue 266](https://github.com/information-artifact-ontology/IAO/issues/266) to move the discussion to https://github.com/information-artifact-ontology/ontology-metadata/issues. The only thing related to the ontology metadata is whether we need to add a new annotation property. If I misunderstood, you can close the issue.

**Comment by matentzn** [comment]
Sorry, I was unclear. I meant the term adoption vs migration discussion, which yeah, should probably be had in the main OBO Foundry repo. I doubt this here is up for much realistic debate. Apologies.

I will close this because I don't think we should debate another annotation property after we have already decided it in OBO Foundry; please re-open if you want to contest the previous decision! Thanks!
