### ISSUE TITLE
Possible to drop reference to GDC?

### ISSUE THREAD

**Issue by sebastianduesing** [information-artifact-ontology/ontology-metadata#177]
As OBI has been working on a transition to use COB as its upper level ontology, we've run into trouble with the way that OMO asserts ICE ([IAO_0000030](http://purl.obolibrary.org/obo/IAO_0000030)) is a subclass of GDC ([BFO_0000031](http://purl.obolibrary.org/obo/BFO_0000031)) in its current release. When imported alongside COB, this injects a reference to BFO_0000031; we're trying to strip out any non-COB BFO references, so having that usage of BFO_0000031 coming in through OMO is non-ideal. Would it be possible for OMO to drop GDC and just use ICE as the highest class in its hierarchy?

**Comment by alanruttenberg** [comment]
It's from GDC that certain relations arise, like concretizes. IAO is incomplete without ICE begin a subclass of GDC. Please consider managing your goal in some other way.

**Comment by matentzn** [comment]
@alanruttenberg, oh, did [IAO_0000030](http://purl.obolibrary.org/obo/IAO_0000030) migrate to OMO? So its not managed by IAO anymore? In this case I will recant my PR - its really not of OMOs business to assert the logical commitment of an IAO class - that should come from IAO itself.

**Comment by jamesaoverton** [comment]
@alanruttenberg The axiom 'ICE subClassOf GDC' is essential to IAO, of course. That's not what this issue is about.

This issue is about removing that axiom from OMO, where it does no work, so that the top-level class in OMO is ICE. We currently have a dangling reference to GDC at the top, e.g. from OLS:

<img width="484" alt="image" src="https://github.com/user-attachments/assets/ab65b545-8d65-4446-a8d1-e3ec29c06d1a">
